[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false"
  GO_VERSION = ""
  PHP_VERSION = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 